# Generated by Django 3.2 on 2021-04-20 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itensvendas',
            name='ordem',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
