# Generated by Django 3.2 on 2021-04-21 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0003_auto_20210421_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='data_nascimento',
            field=models.DateField(),
        ),
    ]
