# Generated by Django 3.2 on 2021-04-21 17:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0004_alter_clientes_data_nascimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendas',
            name='data',
            field=models.DateField(blank=True, default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='vendas',
            name='total',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
